### PR TITLE
updating const to let

### PR DESCRIPTION
**Pull request by ahmedu007**
I'm using this lib with react-native-web. Its not letting me compile since the const is being redefined in the function. Updating the `const` to a `let` to solve the issue and fix the convention.

### CODE REVIEW

**Comment by NsTremblay** [comment]
This was causing react-native 0.56 to crash. Had to apply this patch in order to make it work.

**Comment by jmikulka** [comment]
@ahmedu007 could you please update your commit to include the change from `const` to `let` only?

@obipawan I can confirm this fix works on react-native@0.56.0, would you mind merging it and publishing new version to npm?

**Comment by luskin** [comment]
@obipawan Can you please merge this in? Confirmed this is a RN 0.56 issue and that simple one line fixes it.

simulator screen shot - iphone 6 - 2018-07-16 at 10 44 37

**Comment by obipawan** [comment]
Apologies folks. I'll be pushing out an update in some time.

**Comment by obipawan** [comment]
Available on [v0.0.9](https://github.com/obipawan/react-native-dash/releases/tag/v0.0.9)
Thanks @ahmedu007 for the fix

**Pull request merged**
